[env]
DYLD_LIBRARY_PATH = "{{env.HOMEBREW_PREFIX}}/opt/openssl@3/lib/"

[tools]
python = {version="3.10.11", virtualenv=".venv"}
poetry = {version="1.5.1", pyproject="pyproject.toml"}

[settings]
verbose = true
